# Generated by Django 5.1.2 on 2024-10-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
